service: FacialRecognitionExample
plugins:
  - serverless-plugin-typescript
provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "sns:Publish"
      Resource: "*"
functions:
  facialRecognition:
    handler: handler.facialRecognition
    environment:
      snsTopic: arn:aws:sns:eu-west-1:804937996574:FacialRecognition
    events:
      - stream: arn:aws:kinesis:eu-west-1:804937996574:stream/FacialRecognition